[package]
name = "day-09"
version = "0.1.0"
authors = ["Nicholas Hollett <niax@niax.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
commons = { path = "../commons" }
itertools = "0.9.0"
